### PR TITLE
FT2232H Mini-Module instructions + RPi2 OOCD configuration script

### PR DESCRIPTION
**Pull request by Rostere**
I updated the README files with instructions on how to use the FT2232H Mini-Module. Also modified the OpenOCD configuration script for RPi2 with the correct addresses, and it appears to work correctly for me now.

### CODE REVIEW

**Comment by dwelch67** [comment]
Thanks!   Will try this tonight if I remember....

**Comment by dwelch67** [comment]
you mind educating me on how you figured that out?

**Comment by dwelch67** [comment]
the openocd config changes

**Comment by Rostere** [comment]
I suppose you are referring to the processor addresses? None of the other changes are strictly necessary, I think (apart from the gdb parts if you want to connect via gdb).

I did not really figure it out myself as such. There are quite a few places on the web which point to a "core debug base addresses" at 0x80010000 and so on.

https://www.raspberrypi.org/forums/viewtopic.php?f=72&t=112425
https://kjarvel.wordpress.com/2015/04/29/raspberry-pi-2-bare-metal-multicore-jtag-debugging/
https://www.raspberrypi.org/forums/viewtopic.php?f=72&t=112424

I'm pretty much 100% the first people who "discovered" these addresses were reading the CoreSight ROM table, for example as described on page 7 in this guide to Lauterbach tools: http://www2.lauterbach.com/pdf/arm_app_coresight.pdf The BCM2836 implements the CoreSight architecture, more information on which can be found in ARMs own documentation. I would specifically point at page 68 onwards in http://infocenter.arm.com/help/topic/com.arm.doc.ddi0316d/DDI0316D_dap_lite_trm.pdf or Chapter D5 in http://infocenter.arm.com/help/topic/com.arm.doc.ihi0029d/IHI0029D_coresight_architecture_spec_v2_0.pdf

Kind regards,

Didrik Lundberg

**Comment by dwelch67** [comment]
thanks, I thought I had tried those addresses without success.  Perhaps the  -ircapture 0x01 -irmask 0x0f helped?

Anyway thanks, just dug out my rpi2 so will try this soon.

**Comment by dwelch67** [comment]
works for me as well, thanks again!

**Pull request merged**
